spring:
    profiles:
        active: dev
    application:
        name: newworld

mybatis:
    mapper-locations: classpath*:mapper/**/*.xml
    configuration:
        map-underscore-to-camel-case: true
server:
    port: 6001
logging:
    level:
        root: info
    file:
        name: ${spring.application.name}_${server.port}.log
        path: ../logs
